In [29]:
from transformers import AutoTokenizer
from datasets import load_dataset, load_from_disk
import pandas as pd

In [3]:
model_id = "unb-labia/BERTomelo-ModernBERT-Base-v1"
tokenizer = AutoTokenizer.from_pretrained(model_id)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

# LENER

In [39]:
lener = load_from_disk('../lener_br_local')

In [ ]:
qtds_lener = []
for k in lener.keys():
    for item in lener[k]['tokens']:
        qtds_lener.append({"palavras": len(item), "tokens": tokenizer(item, is_split_into_words=True, return_tensors="pt")['input_ids'].shape[1]})

In [76]:
df_lener = pd.DataFrame(qtds_lener)
df_lener

       palavras  tokens
0            47      70
1            55      78
2            25      38
3            55      79
4            10      17
...         ...     ...
10390        88     137
10391         8      13
10392        17     150
10393         3      29
10394         0       2

[10395 rows x 2 columns]

In [77]:
print('Describe:', df_lener['palavras'].describe())

Describe: count    10395.000000
mean        30.598653
std         35.513078
min          0.000000
25%          6.000000
50%         22.000000
75%         43.000000
max        755.000000
Name: palavras, dtype: float64

In [78]:
print('Describe:', df_lener['tokens'].describe())

Describe: count    10395.000000
mean        54.556614
std         62.554015
min          2.000000
25%         12.000000
50%         38.000000
75%         74.000000
max       1290.000000
Name: tokens, dtype: float64

# ASSIN2

In [67]:
ds_assin2 = load_dataset('nilc-nlp/assin2')
ds_assin2

DatasetDict({
    train: Dataset({
        features: ['sentence_pair_id', 'premise', 'hypothesis', 'relatedness_score', 'entailment_judgment'],
        num_rows: 6500
    })
    test: Dataset({
        features: ['sentence_pair_id', 'premise', 'hypothesis', 'relatedness_score', 'entailment_judgment'],
        num_rows: 2448
    })
    validation: Dataset({
        features: ['sentence_pair_id', 'premise', 'hypothesis', 'relatedness_score', 'entailment_judgment'],
        num_rows: 500
    })
})

In [89]:
qtds_assin2 = []

for k in ds_assin2.keys():
    for item in ds_assin2[k]:
        qtds_assin2.append({"palavras": len(item["premise"].split()) + len(item["hypothesis"].split()), "tokens": tokenizer(item["premise"], item["hypothesis"], return_tensors="pt")['input_ids'].shape[1]})

In [90]:
df_assin2 = pd.DataFrame(qtds_assin2)
df_assin2

      palavras  tokens
0           22      29
1           23      39
2           18      36
3           13      21
4           14      18
...        ...     ...
9443        12      17
9444        16      25
9445        23      32
9446        13      18
9447        19      29

[9448 rows x 2 columns]

In [91]:
print('Describe:', df_assin2['palavras'].describe())

Describe: count    9448.000000
mean       18.470576
std         6.748329
min         7.000000
25%        13.000000
50%        17.000000
75%        22.000000
max        59.000000
Name: palavras, dtype: float64

In [92]:
print('Describe:', df_assin2['tokens'].describe())

Describe: count    9448.000000
mean       26.654953
std         9.253365
min        10.000000
25%        20.000000
50%        25.000000
75%        32.000000
max        81.000000
Name: tokens, dtype: float64